#!/usr/bin/env bash
# A bash script that installs haproxy safely on an ubuntu web server.

sudo apt install --no-install-recommends software-properties-common

sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y

sudo apt install haproxy=2.4.\*
